
export const lightTheme = {
  bgGradient: ["#FFFFFF", "#EDF6FF", "#D7EAFF"],
  textPrimary: "#0B1F4F",
  textSecondary: "#6F88B2",
  iconColor: "#222",
  cardBg: "white",
  shadowColor: "#75B5FF",
  topCard: {
    backgroundColor: "white",
    shadowColor: "#6BAEFF",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  liveCard: {
    backgroundColor: "white",
    shadowColor: "#66AAFF",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  tabActiveBg: "#D7EAFF",
  tabActiveText: "#0A2A4A",
  tabInactiveText: "#6F88B2",
  accent: "#3794FF",
  lineColor: "#B8D9FF",
  modalBg: "white",
};